[connections.qcdb]
dialect = "mysql"
username = "inkaliqc"
password = "qcoke"
host = "192.168.0.70"
database = "qc"

[connections.prodDB]
dialect = "mysql"
username = "tohotec"
password = "tohotec"
host = "192.168.0.70"
port = "3307"
database = "inkalidigitalisasi"